export const sculpturelist = [{
    name:'The Starry Night',
    artist:'Vincent van Gogh',
    description:'แวนโก๊ะเป็นหนึ่งในศิลปินที่มีชื่อเสียงและมีอิทธิพลมากที่สุดในประวัติศาสตร์ศิลปะตะวันตก ผลงานของเขาโดดเด่นด้วยความงดงาม เต็มไปด้วยอารมณ์ความรู้สึก และมีสีสันสดใส แต่ชีวิตจริงของเขากลับหม่นหมองทุกข์ระทม เขาเกิดที่ประเทศเนเธอร์แลนด์ในปี 1853',
    url:'http://www.takieng.com/wp-content/uploads/2017/03/Vincent-van-Gogh-01.jpg',
    alt:'This article is about the 1889 Van Gogh painting. For the similar 1888 Van Gogh painting, see Starry Night Over the Rhône. For the 1850 painting by Jean François Millet, see Starry Night (Millet). For other uses, see Starry Night (disambiguation).',
},
{
    name:'Mona Lisa',
    artist:'Leonardo da Vinci',
    description:'ดา วินชี เป็นศิลปินผู้มีชื่อเสียงมากที่สุดแห่งยุคเรอเนสซองส์ เกิดที่หมู่บ้าน Vinci ใกล้เมืองฟลอเรนซ์ ประเทศอิตาลี เมื่อปี 1452 เขาเติบโตและเรียนศิลปะที่บ้านเกิดจนมีอายุได้ 20 ปีจึงได้เป็นศิลปินมืออาชีพอย่างเต็มตัว',
    url:'http://www.takieng.com/wp-content/uploads/2017/03/Leonardo-da-Vinci-01.jpg',
    alt:'The Mona Lisa is a half-length portrait painting by Italian artist Leonardo da Vinci.',
},
{
    name:'Guernica',
    artist:'Pablo Picasso',
    description:'ปีกัสโซ เป็นผู้ทรงอิทธิพลแห่งศิลปะสมัยใหม่ เกิดเมื่อปี 1881 ที่เมืองมาลากา ประเทศสเปน เขาเติบโตและเรียนหนังสือในสเปน แต่ไปปักหลักอาศัยอยู่ที่ปารีสอย่างถาวรตั้งแต่ปี 1900',
    url:'http://www.takieng.com/wp-content/uploads/2017/03/Pablo-Picasso-01.jpg',
    alt:'ɡernika is a large 1937 oil painting by Spanish artist Pablo Picasso. It is one of his best-known works, regarded by many art critics as the most moving and powerful anti-war painting in history.It is exhibited in the Museo Reina Sofía in Madrid.',
},
{
    name:'David',
    artist:'Michelangelo',
    description:'ไมเคิลแองเจโล เป็นทั้งจิตรกร ประติมากร และสถาปนิก เป็นศิลปินผู้ยิ่งใหญ่แห่งยุคเรอเนสซองส์ทัดเทียมกับเลโอนาร์โด ดา วินชี เขาเกิดเมื่อปี 1475 ที่เมืองอาเรซโซ ประเทศอิตาลี',
    url:'http://www.takieng.com/wp-content/uploads/2017/03/Michelangelo-01.jpg',
    alt:'David is a masterpiece of Italian Renaissance sculpture, created from 1501 to 1504 by Michelangelo.',
},
{
    name:'The Starry Night',
    artist:'Rembrandt',
    description:'แรมบรันต์เป็นทั้งจิตรกร ช่างพิมพ์ และช่างเขียนแบบ เป็นศิลปินผู้ยิ่งใหญ่อีกคนหนึ่งในประวัติศาสตร์ศิลปะ ผลงานของเขามีส่วนทำให้เนเธอร์แลนด์เข้าสู่ยุคทองที่รุ่งเรืองสุดขีดในช่วงศตวรรษที่ 17',
    url:'http://www.takieng.com/wp-content/uploads/2017/03/Rembrandt-01.jpg',
    alt:'Militia Company of District II under the Command of Captain Frans Banninck Cocq, also known as The Shooting Company of Frans Banning Cocq and Willem van Ruytenburch, but commonly referred to as The Night Watch',
},
{
    name:'Girl with a Pearl Earring',
    artist:'Johan Vermeer',
    description:'เฟอร์เมร์ เป็นชาวดัตช์ เกิดเมื่อปี 1632 ที่เมืองเดลฟท์ ประเทศเนเธอร์แลนด์ เขาแต่งงานมีครอบครัวและอาศัยอยู่ที่เมืองเดลฟท์ตลอดชีวิต ไม่มีใครรู้เรื่องราวของเขามากนัก รู้เพียงว่าเขาทุ่มเทให้กับการเขียนภาพ',
    url:'http://www.takieng.com/wp-content/uploads/2017/03/Johan-Vermeer-01.jpg',
    alt:'Girl with a Pearl Earring is an oil painting by Dutch Golden Age painter Johannes Vermeer, dated c. 1665',
},
]